// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgqFesGEVhvmgnA68r1d1xqdqg7SHCA4w',
    appId: '1:265332611171:web:f4873bc4d512161d634056',
    messagingSenderId: '265332611171',
    projectId: 'on-this-day-98e6b',
    authDomain: 'on-this-day-98e6b.firebaseapp.com',
    storageBucket: 'on-this-day-98e6b.firebasestorage.app',
    measurementId: 'G-G0CMEQ10WY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD02tKu3uICMjkoSKoHuBxooR-cxc19Zvs',
    appId: '1:265332611171:android:1d0037c57191e99e634056',
    messagingSenderId: '265332611171',
    projectId: 'on-this-day-98e6b',
    storageBucket: 'on-this-day-98e6b.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDA_neTD7etPPntLrbFo-Rki4d2Nq2JfF4',
    appId: '1:265332611171:ios:fd700fc6ac7a3cbe634056',
    messagingSenderId: '265332611171',
    projectId: 'on-this-day-98e6b',
    storageBucket: 'on-this-day-98e6b.firebasestorage.app',
    iosBundleId: 'com.jevaunharris.onthisday',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDA_neTD7etPPntLrbFo-Rki4d2Nq2JfF4',
    appId: '1:265332611171:ios:53b6a39eb8c607ce634056',
    messagingSenderId: '265332611171',
    projectId: 'on-this-day-98e6b',
    storageBucket: 'on-this-day-98e6b.firebasestorage.app',
    iosBundleId: 'com.example.onThisDayMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgqFesGEVhvmgnA68r1d1xqdqg7SHCA4w',
    appId: '1:265332611171:web:82094e86112a4376634056',
    messagingSenderId: '265332611171',
    projectId: 'on-this-day-98e6b',
    authDomain: 'on-this-day-98e6b.firebaseapp.com',
    storageBucket: 'on-this-day-98e6b.firebasestorage.app',
    measurementId: 'G-75L37B2KNG',
  );
}
